apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-deployment
  labels:
    app: my-app
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp-container
        image: yuribernstein/advisor:ddfde4b23c48bf6915e01daa19b44a9dd5299d70
        ports:
        - containerPort: 8080
